version: '3.8'

services:
  test:
    privileged: true
    build:
      dockerfile: Dockerfile
    volumes:
      - ./shell:/projects/shell
      - ./scheduler:/projects/scheduler
      - ./filesystem:/projects/filesystem